services:
  - type: web
    name: hmd-hermada-hr-solution-inc
    env: python
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true